workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "feature/front-back"'
    - if: '$CI_COMMIT_BRANCH == "test"'
    - when: never

# Image par défaut pour les jobs Node/Frontend
image: node:18

stages:
  - test
  - unit-test
  - build-docker
  - deploy

# 1. STAGE TEST : Vérification de la structure du projet
check-files:
  stage: test
  script:
    - echo "Vérification de l'arborescence..."
    - |
      if [ ! -d backend/tests ] || [ ! -f backend/requirements.txt ]; then 
        echo "Erreur: Structure Backend invalide"; exit 1; 
      fi

# 2. STAGE UNIT-TEST
frontend-jest:
  stage: unit-test
  script:
    - npm install jest jest-environment-jsdom jest-junit
    - npx jest __tests__/unit_test.js --ci --reporters=default --reporters=jest-junit --outputFile=frontend/junit.xml
  artifacts:
    when: always
    reports:
      junit: frontend/junit.xml

backend-test:
  stage: unit-test
  image: python:3.11-slim
  script:
    - cd backend
    # Installation des dépendances incluant pytest-cov et httpx
    - pip install --no-cache-dir -r requirements.txt
    # Lancement des tests avec génération de rapports
    - pytest -v --cov=. --cov-report=xml:coverage.xml --junitxml=junit.xml tests/
  artifacts:
    when: always
    reports:
      junit: backend/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: backend/coverage.xml

recommendation-test:
  stage: unit-test
  image: python:3.11-slim
  script:
    - cd recommendation
    - pip install --no-cache-dir -r requirements.txt
    - pytest -v --cov=. --cov-report=xml:coverage.xml --junitxml=junit.xml tests/
  artifacts:
    when: always
    reports:
      junit: recommendation/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: recommendation/coverage.xml

# 3. STAGE BUILD-DOCKER
build-microservices:
  stage: build-docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    # Construit les images basées sur tes Dockerfiles
    - docker compose build

# 4. STAGE DEPLOY (GitLab Pages pour le Front Orange)
pages:
  stage: deploy
  script:
    - mkdir -p public
    # On expose tous les fichiers du nouveau design orange
    - cp frontend/index.html frontend/style.css frontend/script.js frontend/login.html frontend/register.html public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'