image: alpine:latest

stages:
  - test
  - deploy

job-test:
  stage: test
  script:
  	- cd ./simple_app
  	
  	- if [ ! -f index.html -o ! -f index.html -o ! -f index.html];then
	exit 1; 
  	fi 
  	
  	

deploy:
  stage: deploy
  script:
    - mkdir -p public
    - cp simple_app/index.html simple_app/styles.css simple_app/script.js public/
  artifacts:
    paths:
      - public
  only:
    - main

