apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: opsci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: opsci-frontend
        imagePullPolicy: Never
        ports:
          - containerPort: 80