apiVersion: apps/v1
kind: Deployment
metadata:
  name: reco
  namespace: opsci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reco
  template:
    metadata:
      labels:
        app: reco
    spec:
      containers:
      - name: reco
        image: opsci-reco
        imagePullPolicy: Never
        ports:
          - containerPort: 8001
        env:
          - name: DATABASE_URL
            value: postgresql://user:password@db:5432/opsci